// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assemblies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssembly = `-- name: CreateAssembly :one
INSERT INTO assemblies (plant_id, material_spec_id, code, name, kind, width_um, height_um, depth_um, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, plant_id, code, name, kind, width_um, height_um, depth_um, attributes, created_at, updated_at, material_spec_id
`

type CreateAssemblyParams struct {
	PlantID        uuid.UUID   `json:"plant_id"`
	MaterialSpecID pgtype.UUID `json:"material_spec_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Kind           string      `json:"kind"`
	WidthUm        int64       `json:"width_um"`
	HeightUm       int64       `json:"height_um"`
	DepthUm        int64       `json:"depth_um"`
	Attributes     []byte      `json:"attributes"`
}

func (q *Queries) CreateAssembly(ctx context.Context, arg CreateAssemblyParams) (Assembly, error) {
	row := q.db.QueryRow(ctx, createAssembly,
		arg.PlantID,
		arg.MaterialSpecID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.WidthUm,
		arg.HeightUm,
		arg.DepthUm,
		arg.Attributes,
	)
	var i Assembly
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.WidthUm,
		&i.HeightUm,
		&i.DepthUm,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialSpecID,
	)
	return i, err
}

const createAssemblyComponent = `-- name: CreateAssemblyComponent :one
INSERT INTO assembly_components (
    assembly_id, seq, role, kind, name, material_spec_id, quantity,
    width_um, height_um, depth_um,
    offset_x_um, offset_y_um, offset_z_um, attributes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, assembly_id, seq, role, kind, name, material_spec_id, width_um, height_um, depth_um, offset_x_um, offset_y_um, offset_z_um, attributes, quantity
`

type CreateAssemblyComponentParams struct {
	AssemblyID     uuid.UUID   `json:"assembly_id"`
	Seq            int32       `json:"seq"`
	Role           string      `json:"role"`
	Kind           string      `json:"kind"`
	Name           string      `json:"name"`
	MaterialSpecID pgtype.UUID `json:"material_spec_id"`
	Quantity       int32       `json:"quantity"`
	WidthUm        int64       `json:"width_um"`
	HeightUm       int64       `json:"height_um"`
	DepthUm        int64       `json:"depth_um"`
	OffsetXUm      int64       `json:"offset_x_um"`
	OffsetYUm      int64       `json:"offset_y_um"`
	OffsetZUm      int64       `json:"offset_z_um"`
	Attributes     []byte      `json:"attributes"`
}

func (q *Queries) CreateAssemblyComponent(ctx context.Context, arg CreateAssemblyComponentParams) (AssemblyComponent, error) {
	row := q.db.QueryRow(ctx, createAssemblyComponent,
		arg.AssemblyID,
		arg.Seq,
		arg.Role,
		arg.Kind,
		arg.Name,
		arg.MaterialSpecID,
		arg.Quantity,
		arg.WidthUm,
		arg.HeightUm,
		arg.DepthUm,
		arg.OffsetXUm,
		arg.OffsetYUm,
		arg.OffsetZUm,
		arg.Attributes,
	)
	var i AssemblyComponent
	err := row.Scan(
		&i.ID,
		&i.AssemblyID,
		&i.Seq,
		&i.Role,
		&i.Kind,
		&i.Name,
		&i.MaterialSpecID,
		&i.WidthUm,
		&i.HeightUm,
		&i.DepthUm,
		&i.OffsetXUm,
		&i.OffsetYUm,
		&i.OffsetZUm,
		&i.Attributes,
		&i.Quantity,
	)
	return i, err
}

const getAssembly = `-- name: GetAssembly :one
SELECT id, plant_id, code, name, kind, width_um, height_um, depth_um, attributes, created_at, updated_at, material_spec_id
FROM assemblies
WHERE id = $1
`

func (q *Queries) GetAssembly(ctx context.Context, id uuid.UUID) (Assembly, error) {
	row := q.db.QueryRow(ctx, getAssembly, id)
	var i Assembly
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.WidthUm,
		&i.HeightUm,
		&i.DepthUm,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialSpecID,
	)
	return i, err
}

const listAllAssemblyComponents = `-- name: ListAllAssemblyComponents :many
SELECT id, assembly_id, seq, role, kind, name, material_spec_id, width_um, height_um, depth_um, offset_x_um, offset_y_um, offset_z_um, attributes, quantity
FROM assembly_components
ORDER BY assembly_id, seq
`

func (q *Queries) ListAllAssemblyComponents(ctx context.Context) ([]AssemblyComponent, error) {
	rows, err := q.db.Query(ctx, listAllAssemblyComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssemblyComponent{}
	for rows.Next() {
		var i AssemblyComponent
		if err := rows.Scan(
			&i.ID,
			&i.AssemblyID,
			&i.Seq,
			&i.Role,
			&i.Kind,
			&i.Name,
			&i.MaterialSpecID,
			&i.WidthUm,
			&i.HeightUm,
			&i.DepthUm,
			&i.OffsetXUm,
			&i.OffsetYUm,
			&i.OffsetZUm,
			&i.Attributes,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssemblies = `-- name: ListAssemblies :many
SELECT id, plant_id, code, name, kind, width_um, height_um, depth_um, attributes, created_at, updated_at, material_spec_id
FROM assemblies
ORDER BY code
`

func (q *Queries) ListAssemblies(ctx context.Context) ([]Assembly, error) {
	rows, err := q.db.Query(ctx, listAssemblies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assembly{}
	for rows.Next() {
		var i Assembly
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.WidthUm,
			&i.HeightUm,
			&i.DepthUm,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialSpecID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssemblyComponents = `-- name: ListAssemblyComponents :many
SELECT id, assembly_id, seq, role, kind, name, material_spec_id, width_um, height_um, depth_um, offset_x_um, offset_y_um, offset_z_um, attributes, quantity
FROM assembly_components
WHERE assembly_id = $1
ORDER BY seq
`

func (q *Queries) ListAssemblyComponents(ctx context.Context, assemblyID uuid.UUID) ([]AssemblyComponent, error) {
	rows, err := q.db.Query(ctx, listAssemblyComponents, assemblyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssemblyComponent{}
	for rows.Next() {
		var i AssemblyComponent
		if err := rows.Scan(
			&i.ID,
			&i.AssemblyID,
			&i.Seq,
			&i.Role,
			&i.Kind,
			&i.Name,
			&i.MaterialSpecID,
			&i.WidthUm,
			&i.HeightUm,
			&i.DepthUm,
			&i.OffsetXUm,
			&i.OffsetYUm,
			&i.OffsetZUm,
			&i.Attributes,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
