// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCampaignItem = `-- name: CompleteCampaignItem :one
UPDATE campaign_items
SET status = $2, plan_id = $3, job_id = $4, error = $5, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, seq, name, parts, due_date, priority, status, plan_id, job_id, error, created_at, updated_at
`

type CompleteCampaignItemParams struct {
	ID     uuid.UUID   `json:"id"`
	Status string      `json:"status"`
	PlanID pgtype.UUID `json:"plan_id"`
	JobID  pgtype.UUID `json:"job_id"`
	Error  string      `json:"error"`
}

func (q *Queries) CompleteCampaignItem(ctx context.Context, arg CompleteCampaignItemParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, completeCampaignItem,
		arg.ID,
		arg.Status,
		arg.PlanID,
		arg.JobID,
		arg.Error,
	)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Seq,
		&i.Name,
		&i.Parts,
		&i.DueDate,
		&i.Priority,
		&i.Status,
		&i.PlanID,
		&i.JobID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPendingCampaignItems = `-- name: CountPendingCampaignItems :one
SELECT count(*)::bigint AS pending
FROM campaign_items
WHERE campaign_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingCampaignItems(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCampaignItems, campaignID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const createCampaign = `-- name: CreateCampaign :one

INSERT INTO campaigns (plant_id, code, name, rules, objective, budget_ms, seed, stock, initial_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
`

type CreateCampaignParams struct {
	PlantID      uuid.UUID `json:"plant_id"`
	Code         string    `json:"code"`
	Name         string    `json:"name"`
	Rules        []byte    `json:"rules"`
	Objective    []byte    `json:"objective"`
	BudgetMs     int32     `json:"budget_ms"`
	Seed         int64     `json:"seed"`
	Stock        []byte    `json:"stock"`
	InitialStock []byte    `json:"initial_stock"`
}

// Campaign planning: ordered jobs sharing one stock budget.
func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.PlantID,
		arg.Code,
		arg.Name,
		arg.Rules,
		arg.Objective,
		arg.BudgetMs,
		arg.Seed,
		arg.Stock,
		arg.InitialStock,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.Objective,
		&i.BudgetMs,
		&i.Seed,
		&i.Stock,
		&i.InitialStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createCampaignItem = `-- name: CreateCampaignItem :one
INSERT INTO campaign_items (campaign_id, seq, name, parts, due_date, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, seq, name, parts, due_date, priority, status, plan_id, job_id, error, created_at, updated_at
`

type CreateCampaignItemParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	Seq        int32       `json:"seq"`
	Name       string      `json:"name"`
	Parts      []byte      `json:"parts"`
	DueDate    pgtype.Date `json:"due_date"`
	Priority   int32       `json:"priority"`
}

func (q *Queries) CreateCampaignItem(ctx context.Context, arg CreateCampaignItemParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, createCampaignItem,
		arg.CampaignID,
		arg.Seq,
		arg.Name,
		arg.Parts,
		arg.DueDate,
		arg.Priority,
	)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Seq,
		&i.Name,
		&i.Parts,
		&i.DueDate,
		&i.Priority,
		&i.Status,
		&i.PlanID,
		&i.JobID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaignItem = `-- name: DeleteCampaignItem :execrows
DELETE FROM campaign_items
WHERE id = $1 AND campaign_id = $2 AND status = 'pending'
`

type DeleteCampaignItemParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) DeleteCampaignItem(ctx context.Context, arg DeleteCampaignItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaignItem, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.Objective,
		&i.BudgetMs,
		&i.Seed,
		&i.Stock,
		&i.InitialStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCampaignForUpdate = `-- name: GetCampaignForUpdate :one
SELECT id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
FROM campaigns
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCampaignForUpdate(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForUpdate, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.Objective,
		&i.BudgetMs,
		&i.Seed,
		&i.Stock,
		&i.InitialStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCampaignItem = `-- name: GetCampaignItem :one
SELECT id, campaign_id, seq, name, parts, due_date, priority, status, plan_id, job_id, error, created_at, updated_at
FROM campaign_items
WHERE id = $1
`

func (q *Queries) GetCampaignItem(ctx context.Context, id uuid.UUID) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, getCampaignItem, id)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Seq,
		&i.Name,
		&i.Parts,
		&i.DueDate,
		&i.Priority,
		&i.Status,
		&i.PlanID,
		&i.JobID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignItems = `-- name: ListCampaignItems :many
SELECT id, campaign_id, seq, name, parts, due_date, priority, status, plan_id, job_id, error, created_at, updated_at
FROM campaign_items
WHERE campaign_id = $1
ORDER BY seq
`

func (q *Queries) ListCampaignItems(ctx context.Context, campaignID uuid.UUID) ([]CampaignItem, error) {
	rows, err := q.db.Query(ctx, listCampaignItems, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignItem{}
	for rows.Next() {
		var i CampaignItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Seq,
			&i.Name,
			&i.Parts,
			&i.DueDate,
			&i.Priority,
			&i.Status,
			&i.PlanID,
			&i.JobID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
FROM campaigns
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.Rules,
			&i.Objective,
			&i.BudgetMs,
			&i.Seed,
			&i.Stock,
			&i.InitialStock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCampaignItem = `-- name: NextCampaignItem :one
SELECT id, campaign_id, seq, name, parts, due_date, priority, status, plan_id, job_id, error, created_at, updated_at
FROM campaign_items
WHERE campaign_id = $1 AND status = 'pending'
ORDER BY seq
LIMIT 1
`

func (q *Queries) NextCampaignItem(ctx context.Context, campaignID uuid.UUID) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, nextCampaignItem, campaignID)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Seq,
		&i.Name,
		&i.Parts,
		&i.DueDate,
		&i.Priority,
		&i.Status,
		&i.PlanID,
		&i.JobID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignMeta = `-- name: UpdateCampaignMeta :one
UPDATE campaigns
SET name = COALESCE($2::text, name),
    status = COALESCE($3::text, status),
    updated_at = now()
WHERE id = $1
RETURNING id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
`

type UpdateCampaignMetaParams struct {
	ID     uuid.UUID `json:"id"`
	Name   *string   `json:"name"`
	Status *string   `json:"status"`
}

func (q *Queries) UpdateCampaignMeta(ctx context.Context, arg UpdateCampaignMetaParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignMeta, arg.ID, arg.Name, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.Objective,
		&i.BudgetMs,
		&i.Seed,
		&i.Stock,
		&i.InitialStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateCampaignStock = `-- name: UpdateCampaignStock :one
UPDATE campaigns
SET stock = $2,
    status = $3,
    completed_at = CASE WHEN $3 = 'completed' THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, plant_id, code, name, status, rules, objective, budget_ms, seed, stock, initial_stock, created_at, updated_at, completed_at
`

type UpdateCampaignStockParams struct {
	ID     uuid.UUID `json:"id"`
	Stock  []byte    `json:"stock"`
	Status string    `json:"status"`
}

// Stores the remaining budget after an item ran and moves the campaign to
// active (or completed when no pending items remain).
func (q *Queries) UpdateCampaignStock(ctx context.Context, arg UpdateCampaignStockParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStock, arg.ID, arg.Stock, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Rules,
		&i.Objective,
		&i.BudgetMs,
		&i.Seed,
		&i.Stock,
		&i.InitialStock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
