// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :execrows
UPDATE cut_jobs
SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CancelJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE cut_jobs
SET status = 'running', started_at = now()
WHERE id = (
    SELECT id
    FROM cut_jobs
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, plant_id, status, solver, rules_profile_id, input, result, error, seed, budget_ms, created_by, created_at, started_at, finished_at
`

// Claims the oldest queued job. FOR UPDATE SKIP LOCKED makes several workers
// safe against each other: they never block and never claim the same row.
func (q *Queries) ClaimNextJob(ctx context.Context) (CutJob, error) {
	row := q.db.QueryRow(ctx, claimNextJob)
	var i CutJob
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Status,
		&i.Solver,
		&i.RulesProfileID,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.Seed,
		&i.BudgetMs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO cut_jobs (plant_id, status, solver, input, seed, budget_ms, created_by)
VALUES ($1, 'queued', $2, $3, $4, $5, $6)
RETURNING id, plant_id, status, solver, rules_profile_id, input, result, error, seed, budget_ms, created_by, created_at, started_at, finished_at
`

type CreateJobParams struct {
	PlantID   uuid.UUID   `json:"plant_id"`
	Solver    string      `json:"solver"`
	Input     []byte      `json:"input"`
	Seed      int64       `json:"seed"`
	BudgetMs  int32       `json:"budget_ms"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CutJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.PlantID,
		arg.Solver,
		arg.Input,
		arg.Seed,
		arg.BudgetMs,
		arg.CreatedBy,
	)
	var i CutJob
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Status,
		&i.Solver,
		&i.RulesProfileID,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.Seed,
		&i.BudgetMs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failStaleJobs = `-- name: FailStaleJobs :execrows
UPDATE cut_jobs
SET status = 'failed',
    error = 'worker stopped while this job was running',
    finished_at = now()
WHERE status = 'running'
  AND started_at < now() - make_interval(secs => $1::int)
`

// Called on worker start: jobs left in 'running' by a crash cannot be resumed,
// so they are failed with an explanation instead of blocking the queue forever.
func (q *Queries) FailStaleJobs(ctx context.Context, staleSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleJobs, staleSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, plant_id, status, solver, rules_profile_id, input, result, error, seed, budget_ms, created_by, created_at, started_at, finished_at
FROM cut_jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (CutJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i CutJob
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Status,
		&i.Solver,
		&i.RulesProfileID,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.Seed,
		&i.BudgetMs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobView = `-- name: GetJobView :one
SELECT
    j.id,
    j.status,
    j.solver,
    j.error,
    j.created_at,
    j.started_at,
    j.finished_at,
    p.id      AS plan_id,
    p.metrics AS plan_metrics,
    j.result  AS result
FROM cut_jobs j
LEFT JOIN plans p ON p.job_id = j.id
WHERE j.id = $1
`

type GetJobViewRow struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	Solver      string             `json:"solver"`
	Error       string             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	PlanMetrics []byte             `json:"plan_metrics"`
	Result      []byte             `json:"result"`
}

func (q *Queries) GetJobView(ctx context.Context, id uuid.UUID) (GetJobViewRow, error) {
	row := q.db.QueryRow(ctx, getJobView, id)
	var i GetJobViewRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Solver,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.PlanID,
		&i.PlanMetrics,
		&i.Result,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, plant_id, status, solver, seed, budget_ms, error, created_at, started_at, finished_at
FROM cut_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListJobsRow struct {
	ID         uuid.UUID          `json:"id"`
	PlantID    uuid.UUID          `json:"plant_id"`
	Status     string             `json:"status"`
	Solver     string             `json:"solver"`
	Seed       int64              `json:"seed"`
	BudgetMs   int32              `json:"budget_ms"`
	Error      string             `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.Status,
			&i.Solver,
			&i.Seed,
			&i.BudgetMs,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE cut_jobs
SET status = 'done', result = $2, finished_at = now()
WHERE id = $1
`

type MarkJobDoneParams struct {
	ID     uuid.UUID `json:"id"`
	Result []byte    `json:"result"`
}

func (q *Queries) MarkJobDone(ctx context.Context, arg MarkJobDoneParams) error {
	_, err := q.db.Exec(ctx, markJobDone, arg.ID, arg.Result)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE cut_jobs
SET status = 'failed', error = $2, finished_at = now()
WHERE id = $1
`

type MarkJobFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error string    `json:"error"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.Exec(ctx, markJobFailed, arg.ID, arg.Error)
	return err
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE cut_jobs
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) MarkJobRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobRunning, id)
	return err
}
