// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kpis.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const planKPIs = `-- name: PlanKPIs :one

SELECT
    count(*)                                                                                        AS total_plans,
    count(*) FILTER (WHERE status = 'accepted')                                                     AS accepted_plans,
    coalesce(sum((metrics->>'sheetCount')::numeric) FILTER (WHERE status = 'accepted'), 0)::bigint   AS accepted_sheets,
    coalesce(sum((metrics->>'partsPlaced')::numeric) FILTER (WHERE status = 'accepted'), 0)::bigint  AS accepted_parts,
    coalesce(sum((metrics->>'remnantSheets')::numeric) FILTER (WHERE status = 'accepted'), 0)::bigint AS accepted_remnant_sheets,
    coalesce(sum((metrics->>'stockAreaM2')::numeric) FILTER (WHERE status = 'accepted'), 0)::float8 AS accepted_stock_area_m2,
    coalesce(sum((metrics->>'partAreaM2')::numeric) FILTER (WHERE status = 'accepted'), 0)::float8  AS accepted_part_area_m2,
    coalesce(sum((metrics->>'scrapAreaM2')::numeric) FILTER (WHERE status = 'accepted'), 0)::float8 AS accepted_scrap_area_m2,
    coalesce(sum((metrics->>'offcutAreaM2')::numeric) FILTER (WHERE status = 'accepted'), 0)::float8 AS accepted_offcut_area_m2,
    coalesce(sum((metrics->>'cost')::numeric) FILTER (WHERE status = 'accepted'), 0)::float8        AS accepted_cost,
    coalesce(sum((metrics->>'sheetCount')::numeric), 0)::bigint                                     AS total_sheets,
    coalesce(sum((metrics->>'partsPlaced')::numeric), 0)::bigint                                    AS total_parts_placed,
    coalesce(sum((metrics->>'remnantSheets')::numeric), 0)::bigint                                  AS total_remnant_sheets,
    coalesce(sum((metrics->>'stockAreaM2')::numeric), 0)::float8                                    AS total_stock_area_m2,
    coalesce(sum((metrics->>'partAreaM2')::numeric), 0)::float8                                     AS total_part_area_m2,
    coalesce(sum((metrics->>'scrapAreaM2')::numeric), 0)::float8                                    AS total_scrap_area_m2,
    coalesce(sum((metrics->>'offcutAreaM2')::numeric), 0)::float8                                   AS total_offcut_area_m2,
    coalesce(sum((metrics->>'cost')::numeric), 0)::float8                                           AS total_cost
FROM plans
WHERE created_at >= $1 AND created_at < $2
`

type PlanKPIsParams struct {
	From pgtype.Timestamptz `json:"from"`
	To   pgtype.Timestamptz `json:"to"`
}

type PlanKPIsRow struct {
	TotalPlans            int64   `json:"total_plans"`
	AcceptedPlans         int64   `json:"accepted_plans"`
	AcceptedSheets        int64   `json:"accepted_sheets"`
	AcceptedParts         int64   `json:"accepted_parts"`
	AcceptedRemnantSheets int64   `json:"accepted_remnant_sheets"`
	AcceptedStockAreaM2   float64 `json:"accepted_stock_area_m2"`
	AcceptedPartAreaM2    float64 `json:"accepted_part_area_m2"`
	AcceptedScrapAreaM2   float64 `json:"accepted_scrap_area_m2"`
	AcceptedOffcutAreaM2  float64 `json:"accepted_offcut_area_m2"`
	AcceptedCost          float64 `json:"accepted_cost"`
	TotalSheets           int64   `json:"total_sheets"`
	TotalPartsPlaced      int64   `json:"total_parts_placed"`
	TotalRemnantSheets    int64   `json:"total_remnant_sheets"`
	TotalStockAreaM2      float64 `json:"total_stock_area_m2"`
	TotalPartAreaM2       float64 `json:"total_part_area_m2"`
	TotalScrapAreaM2      float64 `json:"total_scrap_area_m2"`
	TotalOffcutAreaM2     float64 `json:"total_offcut_area_m2"`
	TotalCost             float64 `json:"total_cost"`
}

// Aggregates for the realized-yield dashboard. All metrics are read from the
// JSONB scorecard stored on each plan, so the numbers are exactly what the
// solver reported when the plan was made (or edited).
func (q *Queries) PlanKPIs(ctx context.Context, arg PlanKPIsParams) (PlanKPIsRow, error) {
	row := q.db.QueryRow(ctx, planKPIs, arg.From, arg.To)
	var i PlanKPIsRow
	err := row.Scan(
		&i.TotalPlans,
		&i.AcceptedPlans,
		&i.AcceptedSheets,
		&i.AcceptedParts,
		&i.AcceptedRemnantSheets,
		&i.AcceptedStockAreaM2,
		&i.AcceptedPartAreaM2,
		&i.AcceptedScrapAreaM2,
		&i.AcceptedOffcutAreaM2,
		&i.AcceptedCost,
		&i.TotalSheets,
		&i.TotalPartsPlaced,
		&i.TotalRemnantSheets,
		&i.TotalStockAreaM2,
		&i.TotalPartAreaM2,
		&i.TotalScrapAreaM2,
		&i.TotalOffcutAreaM2,
		&i.TotalCost,
	)
	return i, err
}

const planYieldSeries = `-- name: PlanYieldSeries :many
SELECT
    id,
    created_at,
    (metrics->>'yieldPct')::float8 AS yield_pct,
    (metrics->>'wastePct')::float8 AS waste_pct,
    (metrics->>'cost')::float8     AS cost,
    (metrics->>'sheetCount')::numeric::int AS sheets,
    (metrics->>'partsPlaced')::numeric::int AS parts_placed
FROM plans
WHERE status = 'accepted'
  AND created_at >= $1 AND created_at < $2
ORDER BY created_at
LIMIT $3
`

type PlanYieldSeriesParams struct {
	From  pgtype.Timestamptz `json:"from"`
	To    pgtype.Timestamptz `json:"to"`
	Limit int32              `json:"limit"`
}

type PlanYieldSeriesRow struct {
	ID          uuid.UUID          `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	YieldPct    float64            `json:"yield_pct"`
	WastePct    float64            `json:"waste_pct"`
	Cost        float64            `json:"cost"`
	Sheets      int32              `json:"sheets"`
	PartsPlaced int32              `json:"parts_placed"`
}

func (q *Queries) PlanYieldSeries(ctx context.Context, arg PlanYieldSeriesParams) ([]PlanYieldSeriesRow, error) {
	rows, err := q.db.Query(ctx, planYieldSeries, arg.From, arg.To, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanYieldSeriesRow{}
	for rows.Next() {
		var i PlanYieldSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.YieldPct,
			&i.WastePct,
			&i.Cost,
			&i.Sheets,
			&i.PartsPlaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
