// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materials.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (plant_id, code, name, dimension_profile, attributes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plant_id, code, name, dimension_profile, attributes, is_active, created_at, updated_at
`

type CreateMaterialParams struct {
	PlantID          uuid.UUID `json:"plant_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	DimensionProfile string    `json:"dimension_profile"`
	Attributes       []byte    `json:"attributes"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.PlantID,
		arg.Code,
		arg.Name,
		arg.DimensionProfile,
		arg.Attributes,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.DimensionProfile,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMaterialSpec = `-- name: CreateMaterialSpec :one
INSERT INTO material_specs (material_id, code, name, thickness_um, finish, color, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, material_id, code, name, thickness_um, finish, color, attributes, created_at, updated_at
`

type CreateMaterialSpecParams struct {
	MaterialID  uuid.UUID `json:"material_id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	ThicknessUm int64     `json:"thickness_um"`
	Finish      string    `json:"finish"`
	Color       string    `json:"color"`
	Attributes  []byte    `json:"attributes"`
}

func (q *Queries) CreateMaterialSpec(ctx context.Context, arg CreateMaterialSpecParams) (MaterialSpec, error) {
	row := q.db.QueryRow(ctx, createMaterialSpec,
		arg.MaterialID,
		arg.Code,
		arg.Name,
		arg.ThicknessUm,
		arg.Finish,
		arg.Color,
		arg.Attributes,
	)
	var i MaterialSpec
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Code,
		&i.Name,
		&i.ThicknessUm,
		&i.Finish,
		&i.Color,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, plant_id, code, name, dimension_profile, attributes, is_active, created_at, updated_at
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id uuid.UUID) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.DimensionProfile,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterialSpecs = `-- name: ListMaterialSpecs :many
SELECT id, material_id, code, name, thickness_um, finish, color, attributes, created_at, updated_at
FROM material_specs
ORDER BY code
`

func (q *Queries) ListMaterialSpecs(ctx context.Context) ([]MaterialSpec, error) {
	rows, err := q.db.Query(ctx, listMaterialSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialSpec{}
	for rows.Next() {
		var i MaterialSpec
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Code,
			&i.Name,
			&i.ThicknessUm,
			&i.Finish,
			&i.Color,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterials = `-- name: ListMaterials :many
SELECT id, plant_id, code, name, dimension_profile, attributes, is_active, created_at, updated_at
FROM materials
WHERE is_active
ORDER BY code
`

func (q *Queries) ListMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.Code,
			&i.Name,
			&i.DimensionProfile,
			&i.Attributes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
