// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64              `json:"id"`
	PlantID   pgtype.UUID        `json:"plant_id"`
	Actor     pgtype.UUID        `json:"actor"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  string             `json:"entity_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CutJob struct {
	ID             uuid.UUID          `json:"id"`
	PlantID        uuid.UUID          `json:"plant_id"`
	Status         string             `json:"status"`
	Solver         string             `json:"solver"`
	RulesProfileID pgtype.UUID        `json:"rules_profile_id"`
	Input          []byte             `json:"input"`
	Result         []byte             `json:"result"`
	Error          string             `json:"error"`
	Seed           int64              `json:"seed"`
	BudgetMs       int32              `json:"budget_ms"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Machine struct {
	ID         uuid.UUID          `json:"id"`
	PlantID    uuid.UUID          `json:"plant_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Attributes []byte             `json:"attributes"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Material struct {
	ID               uuid.UUID          `json:"id"`
	PlantID          uuid.UUID          `json:"plant_id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	DimensionProfile string             `json:"dimension_profile"`
	Attributes       []byte             `json:"attributes"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MaterialSpec struct {
	ID          uuid.UUID          `json:"id"`
	MaterialID  uuid.UUID          `json:"material_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	ThicknessUm int64              `json:"thickness_um"`
	Finish      string             `json:"finish"`
	Color       string             `json:"color"`
	Attributes  []byte             `json:"attributes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Part struct {
	ID               uuid.UUID          `json:"id"`
	PlantID          uuid.UUID          `json:"plant_id"`
	MaterialSpecID   pgtype.UUID        `json:"material_spec_id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	FinishedLengthUm int64              `json:"finished_length_um"`
	FinishedWidthUm  int64              `json:"finished_width_um"`
	FinishedHeightUm int64              `json:"finished_height_um"`
	Grain            string             `json:"grain"`
	AllowRotate      bool               `json:"allow_rotate"`
	Priority         int32              `json:"priority"`
	Attributes       []byte             `json:"attributes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PartRouting struct {
	ID               uuid.UUID `json:"id"`
	PartID           uuid.UUID `json:"part_id"`
	Seq              int32     `json:"seq"`
	Operation        string    `json:"operation"`
	AllowanceUm      int64     `json:"allowance_um"`
	AllowancePerEdge bool      `json:"allowance_per_edge"`
	Notes            string    `json:"notes"`
}

type Placement struct {
	ID          uuid.UUID   `json:"id"`
	PlanSheetID uuid.UUID   `json:"plan_sheet_id"`
	PartID      pgtype.UUID `json:"part_id"`
	PartCode    string      `json:"part_code"`
	XUm         int64       `json:"x_um"`
	YUm         int64       `json:"y_um"`
	WUm         int64       `json:"w_um"`
	HUm         int64       `json:"h_um"`
	Rotated     bool        `json:"rotated"`
	Seq         int32       `json:"seq"`
}

type Plan struct {
	ID            uuid.UUID          `json:"id"`
	PlantID       uuid.UUID          `json:"plant_id"`
	JobID         pgtype.UUID        `json:"job_id"`
	Version       int32              `json:"version"`
	Status        string             `json:"status"`
	Name          string             `json:"name"`
	Solver        string             `json:"solver"`
	SolverVersion string             `json:"solver_version"`
	Seed          int64              `json:"seed"`
	Rules         []byte             `json:"rules"`
	Metrics       []byte             `json:"metrics"`
	Notes         []byte             `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
}

type PlanSheet struct {
	ID          uuid.UUID   `json:"id"`
	PlanID      uuid.UUID   `json:"plan_id"`
	SheetIndex  int32       `json:"sheet_index"`
	StockCode   string      `json:"stock_code"`
	Label       string      `json:"label"`
	WidthUm     int64       `json:"width_um"`
	HeightUm    int64       `json:"height_um"`
	Offcuts     []byte      `json:"offcuts"`
	CutSteps    []byte      `json:"cut_steps"`
	StockID     string      `json:"stock_id"`
	StockItemID pgtype.UUID `json:"stock_item_id"`
}

type Plant struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RulesProfile struct {
	ID        uuid.UUID          `json:"id"`
	PlantID   uuid.UUID          `json:"plant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Rules     []byte             `json:"rules"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StockFormat struct {
	ID             uuid.UUID          `json:"id"`
	PlantID        uuid.UUID          `json:"plant_id"`
	MaterialSpecID uuid.UUID          `json:"material_spec_id"`
	Code           string             `json:"code"`
	LengthUm       int64              `json:"length_um"`
	WidthUm        int64              `json:"width_um"`
	HeightUm       int64              `json:"height_um"`
	OnHandQty      int32              `json:"on_hand_qty"`
	CostPerUnit    float64            `json:"cost_per_unit"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StockItem struct {
	ID               uuid.UUID          `json:"id"`
	PlantID          uuid.UUID          `json:"plant_id"`
	FormatID         pgtype.UUID        `json:"format_id"`
	Code             string             `json:"code"`
	Label            string             `json:"label"`
	LengthUm         int64              `json:"length_um"`
	WidthUm          int64              `json:"width_um"`
	HeightUm         int64              `json:"height_um"`
	IsRemnant        bool               `json:"is_remnant"`
	Status           string             `json:"status"`
	Location         string             `json:"location"`
	CostPerUnit      float64            `json:"cost_per_unit"`
	Notes            string             `json:"notes"`
	ParentPlanID     pgtype.UUID        `json:"parent_plan_id"`
	ParentSheetIndex *int32             `json:"parent_sheet_index"`
	ConsumedByPlanID pgtype.UUID        `json:"consumed_by_plan_id"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	PlantID      uuid.UUID          `json:"plant_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
