// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPart = `-- name: CreatePart :one
INSERT INTO parts (
    plant_id, material_spec_id, code, name,
    finished_length_um, finished_width_um, finished_height_um,
    grain, allow_rotate, priority, attributes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, plant_id, material_spec_id, code, name, finished_length_um, finished_width_um, finished_height_um, grain, allow_rotate, priority, attributes, created_at, updated_at
`

type CreatePartParams struct {
	PlantID          uuid.UUID   `json:"plant_id"`
	MaterialSpecID   pgtype.UUID `json:"material_spec_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	FinishedLengthUm int64       `json:"finished_length_um"`
	FinishedWidthUm  int64       `json:"finished_width_um"`
	FinishedHeightUm int64       `json:"finished_height_um"`
	Grain            string      `json:"grain"`
	AllowRotate      bool        `json:"allow_rotate"`
	Priority         int32       `json:"priority"`
	Attributes       []byte      `json:"attributes"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, createPart,
		arg.PlantID,
		arg.MaterialSpecID,
		arg.Code,
		arg.Name,
		arg.FinishedLengthUm,
		arg.FinishedWidthUm,
		arg.FinishedHeightUm,
		arg.Grain,
		arg.AllowRotate,
		arg.Priority,
		arg.Attributes,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.MaterialSpecID,
		&i.Code,
		&i.Name,
		&i.FinishedLengthUm,
		&i.FinishedWidthUm,
		&i.FinishedHeightUm,
		&i.Grain,
		&i.AllowRotate,
		&i.Priority,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartRouting = `-- name: CreatePartRouting :one
INSERT INTO part_routings (part_id, seq, operation, allowance_um, allowance_per_edge, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, part_id, seq, operation, allowance_um, allowance_per_edge, notes
`

type CreatePartRoutingParams struct {
	PartID           uuid.UUID `json:"part_id"`
	Seq              int32     `json:"seq"`
	Operation        string    `json:"operation"`
	AllowanceUm      int64     `json:"allowance_um"`
	AllowancePerEdge bool      `json:"allowance_per_edge"`
	Notes            string    `json:"notes"`
}

func (q *Queries) CreatePartRouting(ctx context.Context, arg CreatePartRoutingParams) (PartRouting, error) {
	row := q.db.QueryRow(ctx, createPartRouting,
		arg.PartID,
		arg.Seq,
		arg.Operation,
		arg.AllowanceUm,
		arg.AllowancePerEdge,
		arg.Notes,
	)
	var i PartRouting
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.Seq,
		&i.Operation,
		&i.AllowanceUm,
		&i.AllowancePerEdge,
		&i.Notes,
	)
	return i, err
}

const getPart = `-- name: GetPart :one
SELECT id, plant_id, material_spec_id, code, name, finished_length_um, finished_width_um, finished_height_um, grain, allow_rotate, priority, attributes, created_at, updated_at
FROM parts
WHERE id = $1
`

func (q *Queries) GetPart(ctx context.Context, id uuid.UUID) (Part, error) {
	row := q.db.QueryRow(ctx, getPart, id)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.MaterialSpecID,
		&i.Code,
		&i.Name,
		&i.FinishedLengthUm,
		&i.FinishedWidthUm,
		&i.FinishedHeightUm,
		&i.Grain,
		&i.AllowRotate,
		&i.Priority,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPartRoutings = `-- name: ListPartRoutings :many
SELECT id, part_id, seq, operation, allowance_um, allowance_per_edge, notes
FROM part_routings
WHERE part_id = $1
ORDER BY seq
`

func (q *Queries) ListPartRoutings(ctx context.Context, partID uuid.UUID) ([]PartRouting, error) {
	rows, err := q.db.Query(ctx, listPartRoutings, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartRouting{}
	for rows.Next() {
		var i PartRouting
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.Seq,
			&i.Operation,
			&i.AllowanceUm,
			&i.AllowancePerEdge,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParts = `-- name: ListParts :many
SELECT id, plant_id, material_spec_id, code, name, finished_length_um, finished_width_um, finished_height_um, grain, allow_rotate, priority, attributes, created_at, updated_at
FROM parts
ORDER BY code
`

func (q *Queries) ListParts(ctx context.Context) ([]Part, error) {
	rows, err := q.db.Query(ctx, listParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Part{}
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.MaterialSpecID,
			&i.Code,
			&i.Name,
			&i.FinishedLengthUm,
			&i.FinishedWidthUm,
			&i.FinishedHeightUm,
			&i.Grain,
			&i.AllowRotate,
			&i.Priority,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
