// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plant.sql

package db

import (
	"context"
)

const createPlant = `-- name: CreatePlant :one
INSERT INTO plants (code, name, timezone)
VALUES ($1, $2, $3)
RETURNING id, code, name, timezone, created_at, updated_at
`

type CreatePlantParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) (Plant, error) {
	row := q.db.QueryRow(ctx, createPlant, arg.Code, arg.Name, arg.Timezone)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultPlant = `-- name: GetDefaultPlant :one
SELECT id, code, name, timezone, created_at, updated_at
FROM plants
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetDefaultPlant(ctx context.Context) (Plant, error) {
	row := q.db.QueryRow(ctx, getDefaultPlant)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
