// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPlan = `-- name: AcceptPlan :one
UPDATE plans
SET status = 'accepted', accepted_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('draft', 'approved')
RETURNING id, plant_id, job_id, version, status, name, solver, solver_version, seed, rules, metrics, notes, created_at, updated_at, accepted_at, parent_plan_id
`

// Freezes a plan: only draft or approved plans can be accepted, and the guard
// makes a second accept a no-op the caller can detect (no rows).
func (q *Queries) AcceptPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, acceptPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.Name,
		&i.Solver,
		&i.SolverVersion,
		&i.Seed,
		&i.Rules,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ParentPlanID,
	)
	return i, err
}

const archivePlan = `-- name: ArchivePlan :execrows
UPDATE plans
SET status = 'archived', updated_at = now()
WHERE id = $1 AND status IN ('draft', 'approved')
`

// Retires a plan version that has been superseded by an edit or re-solve.
func (q *Queries) ArchivePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archivePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO placements (plan_sheet_id, part_id, part_code, x_um, y_um, w_um, h_um, rotated, locked, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, plan_sheet_id, part_id, part_code, x_um, y_um, w_um, h_um, rotated, seq, locked
`

type CreatePlacementParams struct {
	PlanSheetID uuid.UUID   `json:"plan_sheet_id"`
	PartID      pgtype.UUID `json:"part_id"`
	PartCode    string      `json:"part_code"`
	XUm         int64       `json:"x_um"`
	YUm         int64       `json:"y_um"`
	WUm         int64       `json:"w_um"`
	HUm         int64       `json:"h_um"`
	Rotated     bool        `json:"rotated"`
	Locked      bool        `json:"locked"`
	Seq         int32       `json:"seq"`
}

func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (Placement, error) {
	row := q.db.QueryRow(ctx, createPlacement,
		arg.PlanSheetID,
		arg.PartID,
		arg.PartCode,
		arg.XUm,
		arg.YUm,
		arg.WUm,
		arg.HUm,
		arg.Rotated,
		arg.Locked,
		arg.Seq,
	)
	var i Placement
	err := row.Scan(
		&i.ID,
		&i.PlanSheetID,
		&i.PartID,
		&i.PartCode,
		&i.XUm,
		&i.YUm,
		&i.WUm,
		&i.HUm,
		&i.Rotated,
		&i.Seq,
		&i.Locked,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (plant_id, job_id, parent_plan_id, version, status, name, solver, solver_version, seed, rules, metrics, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, plant_id, job_id, version, status, name, solver, solver_version, seed, rules, metrics, notes, created_at, updated_at, accepted_at, parent_plan_id
`

type CreatePlanParams struct {
	PlantID       uuid.UUID   `json:"plant_id"`
	JobID         pgtype.UUID `json:"job_id"`
	ParentPlanID  pgtype.UUID `json:"parent_plan_id"`
	Version       int32       `json:"version"`
	Status        string      `json:"status"`
	Name          string      `json:"name"`
	Solver        string      `json:"solver"`
	SolverVersion string      `json:"solver_version"`
	Seed          int64       `json:"seed"`
	Rules         []byte      `json:"rules"`
	Metrics       []byte      `json:"metrics"`
	Notes         []byte      `json:"notes"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.PlantID,
		arg.JobID,
		arg.ParentPlanID,
		arg.Version,
		arg.Status,
		arg.Name,
		arg.Solver,
		arg.SolverVersion,
		arg.Seed,
		arg.Rules,
		arg.Metrics,
		arg.Notes,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.Name,
		&i.Solver,
		&i.SolverVersion,
		&i.Seed,
		&i.Rules,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ParentPlanID,
	)
	return i, err
}

const createPlanSheet = `-- name: CreatePlanSheet :one
INSERT INTO plan_sheets (plan_id, sheet_index, stock_code, stock_id, stock_item_id, label, width_um, height_um, offcuts, cut_steps)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, plan_id, sheet_index, stock_code, label, width_um, height_um, offcuts, cut_steps, stock_id, stock_item_id
`

type CreatePlanSheetParams struct {
	PlanID      uuid.UUID   `json:"plan_id"`
	SheetIndex  int32       `json:"sheet_index"`
	StockCode   string      `json:"stock_code"`
	StockID     string      `json:"stock_id"`
	StockItemID pgtype.UUID `json:"stock_item_id"`
	Label       string      `json:"label"`
	WidthUm     int64       `json:"width_um"`
	HeightUm    int64       `json:"height_um"`
	Offcuts     []byte      `json:"offcuts"`
	CutSteps    []byte      `json:"cut_steps"`
}

func (q *Queries) CreatePlanSheet(ctx context.Context, arg CreatePlanSheetParams) (PlanSheet, error) {
	row := q.db.QueryRow(ctx, createPlanSheet,
		arg.PlanID,
		arg.SheetIndex,
		arg.StockCode,
		arg.StockID,
		arg.StockItemID,
		arg.Label,
		arg.WidthUm,
		arg.HeightUm,
		arg.Offcuts,
		arg.CutSteps,
	)
	var i PlanSheet
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SheetIndex,
		&i.StockCode,
		&i.Label,
		&i.WidthUm,
		&i.HeightUm,
		&i.Offcuts,
		&i.CutSteps,
		&i.StockID,
		&i.StockItemID,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, plant_id, job_id, version, status, name, solver, solver_version, seed, rules, metrics, notes, created_at, updated_at, accepted_at, parent_plan_id
FROM plans
WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.Name,
		&i.Solver,
		&i.SolverVersion,
		&i.Seed,
		&i.Rules,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ParentPlanID,
	)
	return i, err
}

const getPlanForUpdate = `-- name: GetPlanForUpdate :one
SELECT id, plant_id, job_id, version, status, name, solver, solver_version, seed, rules, metrics, notes, created_at, updated_at, accepted_at, parent_plan_id
FROM plans
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPlanForUpdate(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanForUpdate, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.JobID,
		&i.Version,
		&i.Status,
		&i.Name,
		&i.Solver,
		&i.SolverVersion,
		&i.Seed,
		&i.Rules,
		&i.Metrics,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ParentPlanID,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (plant_id, actor, action, entity, entity_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	PlantID  pgtype.UUID `json:"plant_id"`
	Actor    pgtype.UUID `json:"actor"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID string      `json:"entity_id"`
	Payload  []byte      `json:"payload"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.PlantID,
		arg.Actor,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Payload,
	)
	return err
}

const listPlacements = `-- name: ListPlacements :many
SELECT id, plan_sheet_id, part_id, part_code, x_um, y_um, w_um, h_um, rotated, seq, locked
FROM placements
WHERE plan_sheet_id = $1
ORDER BY seq
`

func (q *Queries) ListPlacements(ctx context.Context, planSheetID uuid.UUID) ([]Placement, error) {
	rows, err := q.db.Query(ctx, listPlacements, planSheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Placement{}
	for rows.Next() {
		var i Placement
		if err := rows.Scan(
			&i.ID,
			&i.PlanSheetID,
			&i.PartID,
			&i.PartCode,
			&i.XUm,
			&i.YUm,
			&i.WUm,
			&i.HUm,
			&i.Rotated,
			&i.Seq,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanSheets = `-- name: ListPlanSheets :many
SELECT id, plan_id, sheet_index, stock_code, label, width_um, height_um, offcuts, cut_steps, stock_id, stock_item_id
FROM plan_sheets
WHERE plan_id = $1
ORDER BY sheet_index
`

func (q *Queries) ListPlanSheets(ctx context.Context, planID uuid.UUID) ([]PlanSheet, error) {
	rows, err := q.db.Query(ctx, listPlanSheets, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanSheet{}
	for rows.Next() {
		var i PlanSheet
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.SheetIndex,
			&i.StockCode,
			&i.Label,
			&i.WidthUm,
			&i.HeightUm,
			&i.Offcuts,
			&i.CutSteps,
			&i.StockID,
			&i.StockItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, plant_id, job_id, version, status, name, solver, solver_version, seed, rules, metrics, notes, created_at, updated_at, accepted_at, parent_plan_id
FROM plans
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.JobID,
			&i.Version,
			&i.Status,
			&i.Name,
			&i.Solver,
			&i.SolverVersion,
			&i.Seed,
			&i.Rules,
			&i.Metrics,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.ParentPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
