// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules_profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultRulesProfiles = `-- name: ClearDefaultRulesProfiles :exec
UPDATE rules_profiles
SET is_default = false, updated_at = now()
WHERE plant_id = $1 AND id <> $2 AND is_default
`

type ClearDefaultRulesProfilesParams struct {
	PlantID uuid.UUID `json:"plant_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) ClearDefaultRulesProfiles(ctx context.Context, arg ClearDefaultRulesProfilesParams) error {
	_, err := q.db.Exec(ctx, clearDefaultRulesProfiles, arg.PlantID, arg.ID)
	return err
}

const createRulesProfile = `-- name: CreateRulesProfile :one
INSERT INTO rules_profiles (plant_id, code, name, rules, objective, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plant_id, code, name, rules, objective, is_default, created_at, updated_at
`

type CreateRulesProfileParams struct {
	PlantID   uuid.UUID `json:"plant_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Rules     []byte    `json:"rules"`
	Objective []byte    `json:"objective"`
	IsDefault bool      `json:"is_default"`
}

type CreateRulesProfileRow struct {
	ID        uuid.UUID          `json:"id"`
	PlantID   uuid.UUID          `json:"plant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Rules     []byte             `json:"rules"`
	Objective []byte             `json:"objective"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRulesProfile(ctx context.Context, arg CreateRulesProfileParams) (CreateRulesProfileRow, error) {
	row := q.db.QueryRow(ctx, createRulesProfile,
		arg.PlantID,
		arg.Code,
		arg.Name,
		arg.Rules,
		arg.Objective,
		arg.IsDefault,
	)
	var i CreateRulesProfileRow
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Rules,
		&i.Objective,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRulesProfile = `-- name: GetRulesProfile :one
SELECT id, plant_id, code, name, rules, objective, is_default, created_at, updated_at
FROM rules_profiles
WHERE id = $1
`

type GetRulesProfileRow struct {
	ID        uuid.UUID          `json:"id"`
	PlantID   uuid.UUID          `json:"plant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Rules     []byte             `json:"rules"`
	Objective []byte             `json:"objective"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRulesProfile(ctx context.Context, id uuid.UUID) (GetRulesProfileRow, error) {
	row := q.db.QueryRow(ctx, getRulesProfile, id)
	var i GetRulesProfileRow
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Rules,
		&i.Objective,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRulesProfiles = `-- name: ListRulesProfiles :many

SELECT id, plant_id, code, name, rules, objective, is_default, created_at, updated_at
FROM rules_profiles
ORDER BY is_default DESC, code
`

type ListRulesProfilesRow struct {
	ID        uuid.UUID          `json:"id"`
	PlantID   uuid.UUID          `json:"plant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Rules     []byte             `json:"rules"`
	Objective []byte             `json:"objective"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Rules profiles: named, reusable constraint + objective presets. They are the
// only place vertical specifics live, so every column here is data, not code.
func (q *Queries) ListRulesProfiles(ctx context.Context) ([]ListRulesProfilesRow, error) {
	rows, err := q.db.Query(ctx, listRulesProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesProfilesRow{}
	for rows.Next() {
		var i ListRulesProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.Code,
			&i.Name,
			&i.Rules,
			&i.Objective,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRulesProfile = `-- name: UpdateRulesProfile :one
UPDATE rules_profiles
SET name       = $2,
    rules      = $3,
    objective  = $4,
    is_default = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, plant_id, code, name, rules, objective, is_default, created_at, updated_at
`

type UpdateRulesProfileParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Rules     []byte    `json:"rules"`
	Objective []byte    `json:"objective"`
	IsDefault bool      `json:"is_default"`
}

type UpdateRulesProfileRow struct {
	ID        uuid.UUID          `json:"id"`
	PlantID   uuid.UUID          `json:"plant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Rules     []byte             `json:"rules"`
	Objective []byte             `json:"objective"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateRulesProfile(ctx context.Context, arg UpdateRulesProfileParams) (UpdateRulesProfileRow, error) {
	row := q.db.QueryRow(ctx, updateRulesProfile,
		arg.ID,
		arg.Name,
		arg.Rules,
		arg.Objective,
		arg.IsDefault,
	)
	var i UpdateRulesProfileRow
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.Code,
		&i.Name,
		&i.Rules,
		&i.Objective,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
