// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_formats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStockFormat = `-- name: CreateStockFormat :one
INSERT INTO stock_formats (plant_id, material_spec_id, code, length_um, width_um, height_um, on_hand_qty, cost_per_unit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plant_id, material_spec_id, code, length_um, width_um, height_um, on_hand_qty, cost_per_unit, is_active, created_at, updated_at
`

type CreateStockFormatParams struct {
	PlantID        uuid.UUID `json:"plant_id"`
	MaterialSpecID uuid.UUID `json:"material_spec_id"`
	Code           string    `json:"code"`
	LengthUm       int64     `json:"length_um"`
	WidthUm        int64     `json:"width_um"`
	HeightUm       int64     `json:"height_um"`
	OnHandQty      int32     `json:"on_hand_qty"`
	CostPerUnit    float64   `json:"cost_per_unit"`
}

func (q *Queries) CreateStockFormat(ctx context.Context, arg CreateStockFormatParams) (StockFormat, error) {
	row := q.db.QueryRow(ctx, createStockFormat,
		arg.PlantID,
		arg.MaterialSpecID,
		arg.Code,
		arg.LengthUm,
		arg.WidthUm,
		arg.HeightUm,
		arg.OnHandQty,
		arg.CostPerUnit,
	)
	var i StockFormat
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.MaterialSpecID,
		&i.Code,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.OnHandQty,
		&i.CostPerUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockFormat = `-- name: GetStockFormat :one
SELECT id, plant_id, material_spec_id, code, length_um, width_um, height_um, on_hand_qty, cost_per_unit, is_active, created_at, updated_at
FROM stock_formats
WHERE id = $1
`

func (q *Queries) GetStockFormat(ctx context.Context, id uuid.UUID) (StockFormat, error) {
	row := q.db.QueryRow(ctx, getStockFormat, id)
	var i StockFormat
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.MaterialSpecID,
		&i.Code,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.OnHandQty,
		&i.CostPerUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockFormatDetail = `-- name: GetStockFormatDetail :one
SELECT
    sf.id,
    sf.plant_id,
    sf.material_spec_id,
    sf.code,
    sf.length_um,
    sf.width_um,
    sf.height_um,
    sf.on_hand_qty,
    sf.cost_per_unit,
    sf.is_active,
    ms.code        AS spec_code,
    ms.thickness_um,
    ms.finish,
    m.code         AS material_code,
    m.name         AS material_name,
    m.dimension_profile
FROM stock_formats sf
JOIN material_specs ms ON ms.id = sf.material_spec_id
JOIN materials m ON m.id = ms.material_id
WHERE sf.id = $1
`

type GetStockFormatDetailRow struct {
	ID               uuid.UUID `json:"id"`
	PlantID          uuid.UUID `json:"plant_id"`
	MaterialSpecID   uuid.UUID `json:"material_spec_id"`
	Code             string    `json:"code"`
	LengthUm         int64     `json:"length_um"`
	WidthUm          int64     `json:"width_um"`
	HeightUm         int64     `json:"height_um"`
	OnHandQty        int32     `json:"on_hand_qty"`
	CostPerUnit      float64   `json:"cost_per_unit"`
	IsActive         bool      `json:"is_active"`
	SpecCode         string    `json:"spec_code"`
	ThicknessUm      int64     `json:"thickness_um"`
	Finish           string    `json:"finish"`
	MaterialCode     string    `json:"material_code"`
	MaterialName     string    `json:"material_name"`
	DimensionProfile string    `json:"dimension_profile"`
}

func (q *Queries) GetStockFormatDetail(ctx context.Context, id uuid.UUID) (GetStockFormatDetailRow, error) {
	row := q.db.QueryRow(ctx, getStockFormatDetail, id)
	var i GetStockFormatDetailRow
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.MaterialSpecID,
		&i.Code,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.OnHandQty,
		&i.CostPerUnit,
		&i.IsActive,
		&i.SpecCode,
		&i.ThicknessUm,
		&i.Finish,
		&i.MaterialCode,
		&i.MaterialName,
		&i.DimensionProfile,
	)
	return i, err
}

const listStockFormats = `-- name: ListStockFormats :many
SELECT
    sf.id,
    sf.plant_id,
    sf.material_spec_id,
    sf.code,
    sf.length_um,
    sf.width_um,
    sf.height_um,
    sf.on_hand_qty,
    sf.cost_per_unit,
    sf.is_active,
    ms.code        AS spec_code,
    ms.thickness_um,
    ms.finish,
    m.code         AS material_code,
    m.name         AS material_name,
    m.dimension_profile
FROM stock_formats sf
JOIN material_specs ms ON ms.id = sf.material_spec_id
JOIN materials m ON m.id = ms.material_id
WHERE sf.is_active
ORDER BY m.code, ms.code, sf.code
`

type ListStockFormatsRow struct {
	ID               uuid.UUID `json:"id"`
	PlantID          uuid.UUID `json:"plant_id"`
	MaterialSpecID   uuid.UUID `json:"material_spec_id"`
	Code             string    `json:"code"`
	LengthUm         int64     `json:"length_um"`
	WidthUm          int64     `json:"width_um"`
	HeightUm         int64     `json:"height_um"`
	OnHandQty        int32     `json:"on_hand_qty"`
	CostPerUnit      float64   `json:"cost_per_unit"`
	IsActive         bool      `json:"is_active"`
	SpecCode         string    `json:"spec_code"`
	ThicknessUm      int64     `json:"thickness_um"`
	Finish           string    `json:"finish"`
	MaterialCode     string    `json:"material_code"`
	MaterialName     string    `json:"material_name"`
	DimensionProfile string    `json:"dimension_profile"`
}

func (q *Queries) ListStockFormats(ctx context.Context) ([]ListStockFormatsRow, error) {
	rows, err := q.db.Query(ctx, listStockFormats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockFormatsRow{}
	for rows.Next() {
		var i ListStockFormatsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.MaterialSpecID,
			&i.Code,
			&i.LengthUm,
			&i.WidthUm,
			&i.HeightUm,
			&i.OnHandQty,
			&i.CostPerUnit,
			&i.IsActive,
			&i.SpecCode,
			&i.ThicknessUm,
			&i.Finish,
			&i.MaterialCode,
			&i.MaterialName,
			&i.DimensionProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeStockOnHand = `-- name: TakeStockOnHand :exec
UPDATE stock_formats
SET on_hand_qty = GREATEST(on_hand_qty - 1, 0), updated_at = now()
WHERE id = $1
`

// Consumes one physical sheet from a format without ever going below zero.
func (q *Queries) TakeStockOnHand(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, takeStockOnHand, id)
	return err
}

const updateStockOnHand = `-- name: UpdateStockOnHand :exec
UPDATE stock_formats
SET on_hand_qty = on_hand_qty + $1, updated_at = now()
WHERE id = $2
`

type UpdateStockOnHandParams struct {
	Delta int32     `json:"delta"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateStockOnHand(ctx context.Context, arg UpdateStockOnHandParams) error {
	_, err := q.db.Exec(ctx, updateStockOnHand, arg.Delta, arg.ID)
	return err
}
