// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeStockItem = `-- name: ConsumeStockItem :execrows
UPDATE stock_items
SET status = 'consumed', consumed_by_plan_id = $2, consumed_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('available', 'reserved')
`

type ConsumeStockItemParams struct {
	ID               uuid.UUID   `json:"id"`
	ConsumedByPlanID pgtype.UUID `json:"consumed_by_plan_id"`
}

// Marks a physical piece used by a plan. Only pieces still in the pool can be
// consumed, so a double accept cannot consume the same remnant twice.
func (q *Queries) ConsumeStockItem(ctx context.Context, arg ConsumeStockItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeStockItem, arg.ID, arg.ConsumedByPlanID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createStockItem = `-- name: CreateStockItem :one
INSERT INTO stock_items (
    plant_id, format_id, code, label, length_um, width_um, height_um,
    is_remnant, status, location, cost_per_unit, notes,
    parent_plan_id, parent_sheet_index
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, plant_id, format_id, code, label, length_um, width_um, height_um, is_remnant, status, location, cost_per_unit, notes, parent_plan_id, parent_sheet_index, consumed_by_plan_id, consumed_at, created_at, updated_at
`

type CreateStockItemParams struct {
	PlantID          uuid.UUID   `json:"plant_id"`
	FormatID         pgtype.UUID `json:"format_id"`
	Code             string      `json:"code"`
	Label            string      `json:"label"`
	LengthUm         int64       `json:"length_um"`
	WidthUm          int64       `json:"width_um"`
	HeightUm         int64       `json:"height_um"`
	IsRemnant        bool        `json:"is_remnant"`
	Status           string      `json:"status"`
	Location         string      `json:"location"`
	CostPerUnit      float64     `json:"cost_per_unit"`
	Notes            string      `json:"notes"`
	ParentPlanID     pgtype.UUID `json:"parent_plan_id"`
	ParentSheetIndex *int32      `json:"parent_sheet_index"`
}

func (q *Queries) CreateStockItem(ctx context.Context, arg CreateStockItemParams) (StockItem, error) {
	row := q.db.QueryRow(ctx, createStockItem,
		arg.PlantID,
		arg.FormatID,
		arg.Code,
		arg.Label,
		arg.LengthUm,
		arg.WidthUm,
		arg.HeightUm,
		arg.IsRemnant,
		arg.Status,
		arg.Location,
		arg.CostPerUnit,
		arg.Notes,
		arg.ParentPlanID,
		arg.ParentSheetIndex,
	)
	var i StockItem
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.FormatID,
		&i.Code,
		&i.Label,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.IsRemnant,
		&i.Status,
		&i.Location,
		&i.CostPerUnit,
		&i.Notes,
		&i.ParentPlanID,
		&i.ParentSheetIndex,
		&i.ConsumedByPlanID,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockItem = `-- name: GetStockItem :one
SELECT
    si.id, si.plant_id, si.format_id, si.code, si.label, si.length_um, si.width_um, si.height_um, si.is_remnant, si.status, si.location, si.cost_per_unit, si.notes, si.parent_plan_id, si.parent_sheet_index, si.consumed_by_plan_id, si.consumed_at, si.created_at, si.updated_at,
    sf.code           AS format_code,
    ms.code           AS spec_code,
    m.code            AS material_code,
    m.dimension_profile
FROM stock_items si
LEFT JOIN stock_formats sf ON sf.id = si.format_id
LEFT JOIN material_specs ms ON ms.id = sf.material_spec_id
LEFT JOIN materials m ON m.id = ms.material_id
WHERE si.id = $1
`

type GetStockItemRow struct {
	ID               uuid.UUID          `json:"id"`
	PlantID          uuid.UUID          `json:"plant_id"`
	FormatID         pgtype.UUID        `json:"format_id"`
	Code             string             `json:"code"`
	Label            string             `json:"label"`
	LengthUm         int64              `json:"length_um"`
	WidthUm          int64              `json:"width_um"`
	HeightUm         int64              `json:"height_um"`
	IsRemnant        bool               `json:"is_remnant"`
	Status           string             `json:"status"`
	Location         string             `json:"location"`
	CostPerUnit      float64            `json:"cost_per_unit"`
	Notes            string             `json:"notes"`
	ParentPlanID     pgtype.UUID        `json:"parent_plan_id"`
	ParentSheetIndex *int32             `json:"parent_sheet_index"`
	ConsumedByPlanID pgtype.UUID        `json:"consumed_by_plan_id"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FormatCode       *string            `json:"format_code"`
	SpecCode         *string            `json:"spec_code"`
	MaterialCode     *string            `json:"material_code"`
	DimensionProfile *string            `json:"dimension_profile"`
}

func (q *Queries) GetStockItem(ctx context.Context, id uuid.UUID) (GetStockItemRow, error) {
	row := q.db.QueryRow(ctx, getStockItem, id)
	var i GetStockItemRow
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.FormatID,
		&i.Code,
		&i.Label,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.IsRemnant,
		&i.Status,
		&i.Location,
		&i.CostPerUnit,
		&i.Notes,
		&i.ParentPlanID,
		&i.ParentSheetIndex,
		&i.ConsumedByPlanID,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormatCode,
		&i.SpecCode,
		&i.MaterialCode,
		&i.DimensionProfile,
	)
	return i, err
}

const listAvailableRemnants = `-- name: ListAvailableRemnants :many
SELECT si.id, si.plant_id, si.format_id, si.code, si.label, si.length_um, si.width_um, si.height_um, si.is_remnant, si.status, si.location, si.cost_per_unit, si.notes, si.parent_plan_id, si.parent_sheet_index, si.consumed_by_plan_id, si.consumed_at, si.created_at, si.updated_at
FROM stock_items si
LEFT JOIN stock_formats sf ON sf.id = si.format_id
WHERE si.plant_id = $1
  AND si.status = 'available'
  AND si.is_remnant
  AND ($2::uuid IS NULL
       OR sf.material_spec_id = $2::uuid)
ORDER BY si.created_at, si.id
`

type ListAvailableRemnantsParams struct {
	PlantID        uuid.UUID   `json:"plant_id"`
	MaterialSpecID pgtype.UUID `json:"material_spec_id"`
}

// The remnant-first input for a solve: available, labelled leftovers for a
// plant, optionally limited to one material spec.
func (q *Queries) ListAvailableRemnants(ctx context.Context, arg ListAvailableRemnantsParams) ([]StockItem, error) {
	rows, err := q.db.Query(ctx, listAvailableRemnants, arg.PlantID, arg.MaterialSpecID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockItem{}
	for rows.Next() {
		var i StockItem
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.FormatID,
			&i.Code,
			&i.Label,
			&i.LengthUm,
			&i.WidthUm,
			&i.HeightUm,
			&i.IsRemnant,
			&i.Status,
			&i.Location,
			&i.CostPerUnit,
			&i.Notes,
			&i.ParentPlanID,
			&i.ParentSheetIndex,
			&i.ConsumedByPlanID,
			&i.ConsumedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockItems = `-- name: ListStockItems :many

SELECT
    si.id, si.plant_id, si.format_id, si.code, si.label, si.length_um, si.width_um, si.height_um, si.is_remnant, si.status, si.location, si.cost_per_unit, si.notes, si.parent_plan_id, si.parent_sheet_index, si.consumed_by_plan_id, si.consumed_at, si.created_at, si.updated_at,
    sf.code           AS format_code,
    ms.code           AS spec_code,
    m.code            AS material_code,
    m.dimension_profile
FROM stock_items si
LEFT JOIN stock_formats sf ON sf.id = si.format_id
LEFT JOIN material_specs ms ON ms.id = sf.material_spec_id
LEFT JOIN materials m ON m.id = ms.material_id
WHERE si.plant_id = $1
  AND ($2::text IS NULL OR si.status = $2::text)
  AND ($3::boolean IS NULL OR si.is_remnant = $3::boolean)
ORDER BY si.is_remnant DESC, si.created_at DESC, si.id
`

type ListStockItemsParams struct {
	PlantID   uuid.UUID `json:"plant_id"`
	Status    *string   `json:"status"`
	IsRemnant *bool     `json:"is_remnant"`
}

type ListStockItemsRow struct {
	ID               uuid.UUID          `json:"id"`
	PlantID          uuid.UUID          `json:"plant_id"`
	FormatID         pgtype.UUID        `json:"format_id"`
	Code             string             `json:"code"`
	Label            string             `json:"label"`
	LengthUm         int64              `json:"length_um"`
	WidthUm          int64              `json:"width_um"`
	HeightUm         int64              `json:"height_um"`
	IsRemnant        bool               `json:"is_remnant"`
	Status           string             `json:"status"`
	Location         string             `json:"location"`
	CostPerUnit      float64            `json:"cost_per_unit"`
	Notes            string             `json:"notes"`
	ParentPlanID     pgtype.UUID        `json:"parent_plan_id"`
	ParentSheetIndex *int32             `json:"parent_sheet_index"`
	ConsumedByPlanID pgtype.UUID        `json:"consumed_by_plan_id"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FormatCode       *string            `json:"format_code"`
	SpecCode         *string            `json:"spec_code"`
	MaterialCode     *string            `json:"material_code"`
	DimensionProfile *string            `json:"dimension_profile"`
}

// Physical stock pieces: full sheets from a format and labelled remnants.
// A stock_formats row is a catalog size; a stock_items row is one piece.
func (q *Queries) ListStockItems(ctx context.Context, arg ListStockItemsParams) ([]ListStockItemsRow, error) {
	rows, err := q.db.Query(ctx, listStockItems, arg.PlantID, arg.Status, arg.IsRemnant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockItemsRow{}
	for rows.Next() {
		var i ListStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantID,
			&i.FormatID,
			&i.Code,
			&i.Label,
			&i.LengthUm,
			&i.WidthUm,
			&i.HeightUm,
			&i.IsRemnant,
			&i.Status,
			&i.Location,
			&i.CostPerUnit,
			&i.Notes,
			&i.ParentPlanID,
			&i.ParentSheetIndex,
			&i.ConsumedByPlanID,
			&i.ConsumedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FormatCode,
			&i.SpecCode,
			&i.MaterialCode,
			&i.DimensionProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockItem = `-- name: UpdateStockItem :one
UPDATE stock_items
SET label     = COALESCE($2::text, label),
    location  = COALESCE($3::text, location),
    status    = COALESCE($4::text, status),
    notes     = COALESCE($5::text, notes),
    updated_at = now()
WHERE id = $1
RETURNING id, plant_id, format_id, code, label, length_um, width_um, height_um, is_remnant, status, location, cost_per_unit, notes, parent_plan_id, parent_sheet_index, consumed_by_plan_id, consumed_at, created_at, updated_at
`

type UpdateStockItemParams struct {
	ID       uuid.UUID `json:"id"`
	Label    *string   `json:"label"`
	Location *string   `json:"location"`
	Status   *string   `json:"status"`
	Notes    *string   `json:"notes"`
}

func (q *Queries) UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) (StockItem, error) {
	row := q.db.QueryRow(ctx, updateStockItem,
		arg.ID,
		arg.Label,
		arg.Location,
		arg.Status,
		arg.Notes,
	)
	var i StockItem
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.FormatID,
		&i.Code,
		&i.Label,
		&i.LengthUm,
		&i.WidthUm,
		&i.HeightUm,
		&i.IsRemnant,
		&i.Status,
		&i.Location,
		&i.CostPerUnit,
		&i.Notes,
		&i.ParentPlanID,
		&i.ParentSheetIndex,
		&i.ConsumedByPlanID,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
